node('SLAVE') {
    def skip=true
    stage('Code Check-Out'){
        if (! skip) {
            dir('DEVELOPMENT') {
                git 'https://github.com/citb34/studentapp-ui.git'
            }
        }
    }

    stage("Compile") {
        if (! skip) {
            dir('DEVELOPMENT') {
                sh '''
    mvn compile
    '''
            }
        }
    }
    
    stage('Code Quality Check') {
        if (! skip) {
            dir('DEVELOPMENT') {
                sh '''
    mvn sonar:sonar \
    -Dsonar.projectKey=citb34_studentapp-ui \
    -Dsonar.organization=citb34 \
    -Dsonar.host.url=https://sonarcloud.io \
    -Dsonar.login=a5ca9e6d4961c7a723106943812895d053987acf
    '''
            }
        }
    }

    stage("Build") {
        if (! skip) {
            dir('DEVELOPMENT') {
                sh '''
    mvn package
    '''
            }
        }
    }

    stage('Create-Test-Environment') {
        withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'TERRAFORM-CREDENTIALS',
    usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD']]) {
        dir('TERRAFORM'){
            git 'https://github.com/citb34/Terraform.git'
            sh '''
                export AWS_ACCESS_KEY_ID="$USERNAME"
                export AWS_SECRET_ACCESS_KEY="$PASSWORD"
                cd stack-asg
                terraform init
                terraform apply -auto-approve -var-file=variables/dev.tfvars
                terraform output elb >/tmp/elb
            '''
            env.ELB = sh (
                script: 'cat /tmp/elb',
                returnStdout: true
                ).trim()
            }
        }
    }

    stage('Api-Testing') {
        dir('TESTING'){
            git 'https://github.com/citb34/selenium-sauce-labs.git'
            sh '''
                python scripts/api-tests.py $ELB
            '''
            }
    }

    stage('UI-Testing') {
        withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'TERRAFORM-CREDENTIALS',
    usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD']]) {
            dir('TESTING'){
                git 'https://github.com/citb34/selenium-sauce-labs.git'
                sh '''
                    sed -i -e "s/IPADDRESS/$ELB/" src/test/java/framework/CrudStudent.java
                    mvn clean install "-Dremote=true" "-DseleniumGridURL=http://USERNAME:KEY@ondemand.saucelabs.com:80/wd/hub" "-Dplatform=Windows" "-Dbrowser=Chrome" "-Dbrowserversion=51" "-Doverwrite.binaries=true"
                '''
                }
    }
    }
}
//
//